name: release CI, CD workflow 
on: 
  push:
    branches: [ "release"]
  pull_request:
    branches: [ "release"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: CI
        run: npm ci
      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: make .env 
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NG_APP_KEY : ${{ secrets.OPENAI_KEY }}
          file_name: .env
          fail_on_empty: false
          
      - name: build angular, output in dist/openai
        run: |
          npm run build
      
      - name: show dir, .env file
        run: |
          ls -la 
          
      - name: download, run httpd image, container name serving_base
        run: |
          docker run -d --name serving_base httpd
          
      - name: cp angular build to container
        run: |
          docker cp dist/openai/.  serving_base:/usr/local/apache2/htdocs
          
      - name: Build the custom Docker image
        run: docker commit --change "ENV MODEL_NAME openai" serving_base ${{secrets.DOCKER_USER}}/openai:${{github.sha}}

      - name: show docker images
        run: docker images

      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
          
      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/openai:${{github.sha}}
      
