name: release CI, CD workflow 
on: 
  push:
    branches: [ "release"]
  pull_request:
    branches: [ "release"]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: CI
        run: npm ci
      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: make .env 
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_NG_APP_KEY : ${{ secrets.OPENAI_KEY }}
          file_name: .env
          fail_on_empty: false
      - name: build angular, output in htdocs directory
        run: |
          npm run build --output-dir=htdocs
      
      - name: show dir, .env file
        run: |
          ls -la
        
      - name: download, run httpd image, container name serving_base
        run: |
          docker run -d --name serving_base httpd
      - name: cp angular build to container
        run: |
          docker cp htdocs  serving_base:/usr/local/apache2/
          
          
